# Generated by Django 5.0.7 on 2026-05-17 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=20, verbose_name='学号（冗余）')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='班级（冗余）')),
                ('student_name', models.CharField(blank=True, max_length=50, verbose_name='姓名（冗余）')),
                ('chapter_no', models.IntegerField(verbose_name='章号')),
                ('chapter_name', models.CharField(blank=True, max_length=100, verbose_name='章名')),
                ('section_no', models.IntegerField(verbose_name='节号')),
                ('section_name', models.CharField(blank=True, max_length=100, verbose_name='节名')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='成绩')),
                ('source', models.CharField(choices=[('auto_script', '自动评分'), ('manual', '手动录入'), ('import', 'Excel导入')], default='auto_script', max_length=20, verbose_name='来源')),
                ('evaluator', models.CharField(blank=True, max_length=100, verbose_name='评分机标识/教师')),
                ('details', models.TextField(blank=True, verbose_name='评分详情')),
                ('original_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='原始分数')),
                ('modified_at', models.DateTimeField(blank=True, null=True, verbose_name='修改时间')),
                ('modify_reason', models.CharField(blank=True, max_length=255, verbose_name='修改原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_scores', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.section', verbose_name='所属节')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'scores',
                'ordering': ['chapter_no', 'section_no', 'student_no'],
                'unique_together': {('student', 'section')},
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='原分数')),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='新分数')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='修改原因')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
                ('score_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='scores.score', verbose_name='成绩记录')),
            ],
            options={
                'verbose_name': '成绩修改历史',
                'verbose_name_plural': '成绩修改历史',
                'db_table': 'score_history',
            },
        ),
    ]
