# Generated by Django 5.0.7 on 2026-05-17 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('scores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='score',
            name='score_type',
            field=models.CharField(choices=[('regular', '总成绩'), ('experiment', '实验成绩')], default='regular', max_length=20, verbose_name='成绩类型'),
        ),
        migrations.AlterField(
            model_name='score',
            name='source',
            field=models.CharField(choices=[('auto_script', '自动评分'), ('manual', '手动录入'), ('import', 'Excel导入'), ('experiment', '实验成绩')], default='auto_script', max_length=20, verbose_name='来源'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('student', 'section', 'score_type')},
        ),
    ]
