# Generated by Django 5.0.7 on 2026-05-17 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('fill', '填空题'), ('essay', '简答题'), ('programming', '编程题'), ('attachment', '附件题')], max_length=20, verbose_name='题型')),
                ('title', models.TextField(verbose_name='题目标题')),
                ('content', models.TextField(blank=True, verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='选择题选项')),
                ('correct_answer', models.TextField(blank=True, verbose_name='客观题答案')),
                ('test_cases', models.JSONField(blank=True, null=True, verbose_name='编程题测试用例')),
                ('max_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='满分')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='编程题时间限制(ms)')),
                ('memory_limit', models.IntegerField(blank=True, null=True, verbose_name='编程题内存限制(MB)')),
                ('allowed_languages', models.JSONField(blank=True, null=True, verbose_name='允许的编程语言')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='答题截止时间')),
                ('allow_resubmit', models.BooleanField(default=True, verbose_name='允许重新提交')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.section', verbose_name='所属节')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['order_num'],
            },
        ),
    ]
