# Generated by Django 5.0.7 on 2026-05-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('section', 'order_num')},
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judgment', '判断题'), ('essay', '简答题')], max_length=20, verbose_name='题型'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='allowed_languages',
        ),
        migrations.RemoveField(
            model_name='question',
            name='memory_limit',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_cases',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time_limit',
        ),
    ]
