# Generated by Django 5.0.7 on 2026-05-17 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('description', models.TextField(blank=True, verbose_name='课程描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已发布'), ('archived', '已归档')], default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='授课教师')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_no', models.IntegerField(verbose_name='章序号')),
                ('title', models.CharField(max_length=100, verbose_name='章标题')),
                ('sequence', models.IntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='所属课程')),
            ],
            options={
                'verbose_name': '章',
                'verbose_name_plural': '章',
                'db_table': 'chapters',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_no', models.IntegerField(verbose_name='节序号')),
                ('title', models.CharField(max_length=100, verbose_name='节标题')),
                ('sequence', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否为当前激活节')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.chapter', verbose_name='所属章')),
            ],
            options={
                'verbose_name': '节',
                'verbose_name_plural': '节',
                'db_table': 'sections',
                'ordering': ['sequence'],
            },
        ),
    ]
